configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-floral-leaf-a5zkkxwm.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=Ho5CmQPxe3Or
  - configuration:
      name: edamam
      app_id: c3f53422
      app_key: c19a2f5dc7a8bb156d0f2025ba57cd64
